USE [master]
GO
/****** Object:  Database [Arquitectura4Capas]    Script Date: 04/05/2024 19:01:11 ******/
CREATE DATABASE [Arquitectura4Capas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Arquitectura4Capas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Arquitectura4Capas.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Arquitectura4Capas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Arquitectura4Capas_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Arquitectura4Capas] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Arquitectura4Capas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Arquitectura4Capas] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET ARITHABORT OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Arquitectura4Capas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Arquitectura4Capas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Arquitectura4Capas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Arquitectura4Capas] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET RECOVERY FULL 
GO
ALTER DATABASE [Arquitectura4Capas] SET  MULTI_USER 
GO
ALTER DATABASE [Arquitectura4Capas] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Arquitectura4Capas] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Arquitectura4Capas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Arquitectura4Capas] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Arquitectura4Capas] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Arquitectura4Capas] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Arquitectura4Capas', N'ON'
GO
ALTER DATABASE [Arquitectura4Capas] SET QUERY_STORE = ON
GO
ALTER DATABASE [Arquitectura4Capas] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Arquitectura4Capas]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 04/05/2024 19:01:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[ProductoId] [int] NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Precio] [float] NOT NULL,
 CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED 
(
	[ProductoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 04/05/2024 19:01:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[UsuarioId] [int] NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[DNI] [int] NOT NULL,
	[ProductoId] [int] NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[UsuarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Arquitectura4Capas] SET  READ_WRITE 
GO
